// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCNY6Iu20kIoDp-gN5GTE54vea4fi6X10Y',
    appId: '1:31406524389:web:f381972a0942917767110c',
    messagingSenderId: '31406524389',
    projectId: 'zizzle-1ad7c',
    authDomain: 'zizzle-1ad7c.firebaseapp.com',
    storageBucket: 'zizzle-1ad7c.appspot.com',
    measurementId: 'G-Z8YDNCRD7T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDs1ThntWTWHeazKZUSn1BHcGvWJQq4fFk',
    appId: '1:31406524389:android:224b275fb5e4e8e367110c',
    messagingSenderId: '31406524389',
    projectId: 'zizzle-1ad7c',
    storageBucket: 'zizzle-1ad7c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyABTmjyOyNPkBBdcsIRtgTwze36fz8D2LM',
    appId: '1:31406524389:ios:690102ef62b5ad4067110c',
    messagingSenderId: '31406524389',
    projectId: 'zizzle-1ad7c',
    storageBucket: 'zizzle-1ad7c.appspot.com',
    iosBundleId: 'com.InbredTechno.Zizzle',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyABTmjyOyNPkBBdcsIRtgTwze36fz8D2LM',
    appId: '1:31406524389:ios:af9e06b56469649a67110c',
    messagingSenderId: '31406524389',
    projectId: 'zizzle-1ad7c',
    storageBucket: 'zizzle-1ad7c.appspot.com',
    iosBundleId: 'com.example.newapp.RunnerTests',
  );
}
